Associacoes/config/routes.rb
Rails.application.routes.draw do
  resources :children
  resources :fathers

end

Associacoes/app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :father
end

Associacoes/app/models/father.rb
class Father < ActiveRecord::Base
    has_many :children
end

Associacoes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Associacoes/app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_child, only: [:show, :edit, :update, :destroy]
  before_action :set_father, only: [:edit, :update, :new]

  # GET /children
  # GET /children.json
  def index
    @children = Child.all
  end

  # GET /children/1
  # GET /children/1.json
  def show
  end

  # GET /children/new
  def new
    @child = Child.new
  end

  # GET /children/1/edit
  def edit
  end

  # POST /children
  # POST /children.json
  def create
    @child = Child.new(child_params)

    respond_to do |format|
      if @child.save
        format.html { redirect_to @child, notice: 'Child was successfully created.' }
        format.json { render :show, status: :created, location: @child }
      else
        format.html { render :new }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /children/1
  # PATCH/PUT /children/1.json
  def update
    respond_to do |format|
      if @child.update(child_params)
        format.html { redirect_to @child, notice: 'Child was successfully updated.' }
        format.json { render :show, status: :ok, location: @child }
      else
        format.html { render :edit }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1
  # DELETE /children/1.json
  def destroy
    @child.destroy
    respond_to do |format|
      format.html { redirect_to children_url, notice: 'Child was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child
      @child = Child.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def child_params
      params.require(:child).permit(:name, :sexo, :father_id)
    end
    def set_father
      @fathers = Father.all
    end
    
end

Associacoes/app/controllers/fathers_controller.rb
class FathersController < ApplicationController
  before_action :set_father, only: [:show, :edit, :update, :destroy]

  # GET /fathers
  # GET /fathers.json
  def index
    @fathers = Father.all
  end

  # GET /fathers/1
  # GET /fathers/1.json
  def show
  end

  # GET /fathers/new
  def new
    @father = Father.new
  end

  # GET /fathers/1/edit
  def edit
  end

  # POST /fathers
  # POST /fathers.json
  def create
    @father = Father.new(father_params)

    respond_to do |format|
      if @father.save
        format.html { redirect_to @father, notice: 'Father was successfully created.' }
        format.json { render :show, status: :created, location: @father }
      else
        format.html { render :new }
        format.json { render json: @father.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fathers/1
  # PATCH/PUT /fathers/1.json
  def update
    respond_to do |format|
      if @father.update(father_params)
        format.html { redirect_to @father, notice: 'Father was successfully updated.' }
        format.json { render :show, status: :ok, location: @father }
      else
        format.html { render :edit }
        format.json { render json: @father.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fathers/1
  # DELETE /fathers/1.json
  def destroy
    @father.destroy
    respond_to do |format|
      format.html { redirect_to fathers_url, notice: 'Father was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_father
      @father = Father.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def father_params
      params.require(:father).permit(:name)
    end
end

Associacoes/app/helpers/application_helper.rb
module ApplicationHelper
    def pegar_sexo(sexo)
        html = ""
        if sexo == 'M'
            html = "Masculino"
        elsif sexo == 'F'
            html = "Feminino"
        end
        html
    end
end

Associacoes/app/helpers/children_helper.rb
module ChildrenHelper
end

Associacoes/app/helpers/fathers_helper.rb
module FathersHelper
end

Associacoes/app/views/children/_form.html.erb
<%= form_for(@child) do |f| %>
  <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
      <% @child.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br>
    <%= f.select(:sexo, options_for_select([["Masculino", "M"], ["Feminino", "F"]], @child.sexo), {include_blank: "Selecione"}) %>
  </div>
  <div class="field">
    <%= f.label :father_id %><br>
    <%= f.collection_select(:father_id, @fathers, :id, :name, include_blank: "Selecione") %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Associacoes/app/views/children/edit.html.erb
<h1>Editing Child</h1>

<%= render 'form' %>

<%= link_to 'Show', @child %> |
<%= link_to 'Back', children_path %>

Associacoes/app/views/children/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Children</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sexo</th>
      <th>Father</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @children.each do |child| %>
      <tr>
        <td><%= child.name %></td>
        <td><%= child.sexo %></td>
        <td><%= child.father.name %></td>
        <td><%= link_to 'Show', child %></td>
        <td><%= link_to 'Edit', edit_child_path(child) %></td>
        <td><%= link_to 'Destroy', child, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Child', new_child_path %>

Associacoes/app/views/children/new.html.erb
<h1>New Child</h1>

<%= render 'form' %>

<%= link_to 'Back', children_path %>

Associacoes/app/views/children/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @child.name %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @child.sexo %>
</p>

<p>
  <strong>Father:</strong>
  <%= @child.father.name %>
</p>

<%= link_to 'Edit', edit_child_path(@child) %> |
<%= link_to 'Back', children_path %>

Associacoes/app/views/fathers/_form.html.erb
<%= form_for(@father) do |f| %>
  <% if @father.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@father.errors.count, "error") %> prohibited this father from being saved:</h2>

      <ul>
      <% @father.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Associacoes/app/views/fathers/edit.html.erb
<h1>Editing Father</h1>

<%= render 'form' %>

<%= link_to 'Show', @father %> |
<%= link_to 'Back', fathers_path %>

Associacoes/app/views/fathers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fathers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fathers.each do |father| %>
      <tr>
        <td><%= father.name %></td>
        <td><%= link_to 'Show', father %></td>
        <td><%= link_to 'Edit', edit_father_path(father) %></td>
        <td><%= link_to 'Destroy', father, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Father', new_father_path %>

Associacoes/app/views/fathers/new.html.erb
<h1>New Father</h1>

<%= render 'form' %>

<%= link_to 'Back', fathers_path %>

Associacoes/app/views/fathers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @father.name %>
  <hr>
  
  
  <ul>
  <% @father.children.each do |child| %>
  
      <li><%= "#{child.name} - #{pegar_sexo(child.sexo)}" %></li>
  
  <% end %>
  </ul>
  
  
</p>

<%= link_to 'Edit', edit_father_path(@father) %> |
<%= link_to 'Back', fathers_path %>

Associacoes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Associacoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>